# Starta från en Python-baserad image
FROM python:3.12-slim

# Skapa en icke-root användare
RUN useradd -m flaskuser

# Ange arbetskatalog i containern
WORKDIR /app

# Kopiera kraven för Python-paket
COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt

# Installera Python-paket
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_dev.txt

# Kopiera hela applikationen till containern
COPY src/ .

# Ändra ägare av applikationsfiler till den icke-root användaren
RUN chown -R flaskuser:flaskuser /app

# Byt till icke-root användaren
USER flaskuser

# Exponera porten som Flask körs på
EXPOSE 5678

# Kör applikationen med Gunicorn
CMD ["celery", "-A", "tasks", "worker", "-n", "worker1", "--loglevel=info"]